[handshake.serverbound]
handshake = 0x00

[status.serverbound]
status_request = 0x00
ping_request = 0x01

[status.clientbound]
status_response = 0x00
ping_response = 0x01

[login.clientbound]
disconnect = 0x00
encryption_request = 0x01
login_success = 0x02
set_compression = 0x03
login_plugin_request = 0x04

[login.serverbound]
login_start = 0x00
encryption_response = 0x01

[play.serverbound]

[play.clientbound]
