[package]
name = "netherite-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.140", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }

protocol = { path = "protocol" }
protocol-derive = { path = "protocol-derive" }
chat = { path = "chat" }

serde_json = "1.0.83"
hematite-nbt = "0.5.2"
bytebuffer = "0.2.1"
byteorder = "1.4.3"
toml = "0.5.9"
bytes = "1.2.1"
