[server]
address = "127.0.0.1"
port = 2000
compression-threshold = 256
online-mode = true

[status]
motd = "Welcome to netherite-rs!"
max-players = 100
icon = "server-icon.png"

[game]
default-gamemode = "adventure"
difficulty = "peaceful"
view-distance = 12
simulation-disance = 12
reduce-debug-info = false
enable-respawn-screen = true